import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Readex_Pro } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ReadexPro = Readex_Pro({
	subsets: ['latin'],
	weight: ['200', '300', '400', '500', '600', '700']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ReadexPro.className} antialiased !bg-gradient h-screen w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
